GET https://beautyshop.fly.dev/api/v1/categories/
Content-Type: application/json
###
GET https://beautyshop.fly.dev/api/v1/categories/a8c1a3e6-00eb-4d41-952e-154da97fe2fe/bind_options/
Content-Type: application/json
###
POST  https://beautyshop.fly.dev/api/v1/categories/a8c1a3e6-00eb-4d41-952e-154da97fe2fe/bind_options/
Content-Type: application/json

[
  "ca52475e-4849-408c-9813-cb321e7b462f"
]

