GET https://beautyshop.fly.dev/api/v1/manufacturers/
Content-Type: application/json
###
DELETE https://beautyshop.fly.dev/api/v1/manufacturers/cb4ad30c-142b-4421-81d5-82832b0d4e36/
###
POST https://beautyshop.fly.dev/api/v1/manufacturers/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYyYTcxYTJmNjhiMjU4OWFkN2M3MmViMSIsImlhdCI6MTY2MTAxMTIwMywiZXhwIjoxNjYxNjE2MDAzfQ.dq4DaE91X5YcWrmfFTpTj2EgtkNO900SOApFx4Uwtxk

{
  "name": "string-19",
  "description": "string-19"
}
###


###

###
DELETE https://beautyshop.fly.dev/api/v1/manufacturers/
Content-Type: application/json

###


GET https://beautyshop.fly.dev/api/v1/options/
Content-Type: application/json
###
DELETE https://beautyshop.fly.dev/api/v1/options/5545a859-dc0d-47d7-a2b4-d5b5eb1bde53/
Content-Type: application/json
###
POST https://beautyshop.fly.dev/api/v1/options/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYyYTcxYTJmNjhiMjU4OWFkN2M3MmViMSIsImlhdCI6MTY2MTAxMTIwMywiZXhwIjoxNjYxNjE2MDAzfQ.dq4DaE91X5YcWrmfFTpTj2EgtkNO900SOApFx4Uwtxk

{
  "name": "option-2",
  "parentId": null
}

###
GET https://beautyshop.fly.dev/api/v1/products/
Content-Type: application/json

###
POST https://beautyshop.fly.dev/api/v1/products/
Content-Type: multipart/form-data

{
  "name": "string",
  "description": "string",
  "rating": "",
  "price": "37.28",
  "sku": 2147483647,
  "status": "I",
  "is_luxury": true,
  "manufacturer": "ce59d1ee-291e-4ecb-be87-2f813bc1f5d3",
  "categories": [
    "8fea30f2-792b-4ca0-b257-7f8312b0cf51"
  ],
  "options": ё
}

###


