GET https://beautyshop.fly.dev/api/v1/products/
Content-Type: application/json
###

POST https://beautyshop.fly.dev/api/v1/products/
Content-Type: application/json

{
  "images": [{
    "id": "919e39a9-97ec-4b2a-ac23-2e0a43455894",
    "order": 1
  }],
  "isLuxury": true,
  "siblings": [],
  "mainCard": true,
  "name": "name=1",
  "description": "JSON parse error - Expecting property name enclosed in double quotes: line 4 column 3 (char 72)",
  "rating": "0",
  "price": "10",
  "sku": 4756345,
  "status": "I",
  "sibling_name": "string1",
  "manufacturer": "d3dfe2c0-b407-49e4-8f3c-1c52c63ed906",
  "options": ["f9d128b5-6b29-49d1-9781-ed177d41eff2"],
  "categories": ["514192fd-a5f5-438f-8b4c-2144d4e12220"]
}
###